services:
  web_server:
    build: .
    container_name: web_server
    ports:
      - "5000:5000"
    volumes:
      - .:/my_code
    depends_on:
      - redis_server

  redis_server:
    image:
      redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"



